# deploy a node.js app
FROM node:lts-alpine
# Create app directory
WORKDIR /usr/src/app
COPY package*.json ./
# Install app dependencies
RUN npm install
# Copy files
COPY . .
# Bundle app source
EXPOSE 8080
CMD [ "node", "server.js" ]
