# deploy flask app
FROM python:alpine3.9
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
# Bundle app source
COPY . .
EXPOSE 5001
ENTRYPOINT [ "python" ]
CMD ["server.py"]