# deploy flask app
FROM python:latest
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
# Bundle app source
COPY . .
EXPOSE 5000
CMD [ "flask", "--app", "server" ,"run", "--host=0.0.0.0"]
